app/urls.py
from app.views import *
from django.urls import path

app_name = 'pecuaria'

urlpatterns = [
    path('erro/', error_page, name='error_page'), # Rota para página de erro
    path('criar-conta/', create_account, name='create_account'), # Rota para criar conta
    path('entrar/', login_view, name='login'), # Rota para login
    path('sair/', logout_view, name='logout'), # Rota para logout
    path('', home, name='home'), # Rota para home
    path('lotes/', lotes, name='lotes'), # Rota para página de visualização de lotes
    path('lote/cadastrar/', cadastrar_lote, name='cadastrar_lote'), # Rota para página de cadastro de lotes
    path('lote/atualizar/<int:id>/', atualizar_lote, name='atualizar_lote'), # Rota para página de atualização de lotes
    path('lote/excluir/<int:id>/', excluir_lote, name='excluir_lote'), # Rota que permite excluir um lote
    path('partos/', partos, name='partos'), # Rota para página de visualização de partos
    path('parto/cadastrar/', cadastrar_parto, name='cadastrar_parto'), # Rota para página de cadastro de partos
    path('parto/atualizar/<int:id>/', atualizar_parto, name='atualizar_parto'), # Rota para página de atualização de partos
    path('parto/excluir/<int:id>/', excluir_parto, name='excluir_parto'), # Rota que permite excluir um parto
    path('manejos/', manejos, name='manejos'), # Rota para página de visualização de manejos
    path('manejo/cadastrar/', cadastrar_manejo, name='cadastrar_manejo'), # Rota para página de cadastro de manejos
    path('manejo/atualizar/<int:id>/', atualizar_manejo, name='atualizar_manejo'), # Rota para página de atualização de manejos
    path('manejo/excluir/<int:id>/', excluir_manejo, name='excluir_manejo'), # Rota que permite excluir um manejo
    path('saidas/', saidas, name='saidas'), # Rota para página de visualização de saídas
    path('saida/cadastrar/', cadastrar_saida, name='cadastrar_saida'), # Rota para página de cadastro de saídas
    path('saida/atualizar/<int:id>/', atualizar_saida, name='atualizar_saida'), # Rota para página de atualização de saídas
    path('saida/excluir/<int:id>/', excluir_saida, name='excluir_saida'), # Rota que permite excluir uma saída
    path('animais/', animais, name='animais'), # Rota para página de visualização de animais
    path('animal/', animal_info, name='animal_info'), # Rota para página de visualização das informações de um animal via RFID

    path('api/animal/<str:rfid>/', get_animal, name='get_animal'), # Rota para comunicar com o ESP 8266
    path('api/latest-animal/', latest_animal, name='latest_animal'), # Rota para retornar o último animal lido
]

dev-pecuaria-antigo/config/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

urlpatterns = [
    path("", include("apps.core.urls")),
    path('api-auth/', include('rest_framework.urls'), name='rest_framework'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('pecuaria/', include('app.urls')),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/pages/batches.html
<!-- Template: pages/batches.html -->

<!-- Extends Base Template -->
{% extends 'base/base.html' %}

<!-- Tab Title -->
{% block title %}Lotes{% endblock title %}

<!-- Content -->
{% block content %}
<!-- Botão para cadastrar lote -->
<a class="btn btn-primary mb-3" href="{% url 'pecuaria:cadastrar_lote' %}" role="button">
    <i class="fas fa-plus me-1"></i>
    Cadastrar Lote
</a>

<!-- Tabela de lotes -->
<div class="card p-3">
    <div class="table-responsive pb-3">
        <table id="table-pecuaria" class="table table-striped table-bordered nowrap align-middle text-center mb-0">
            <caption>Lista de lotes</caption>
            <thead>
                <tr>
                    <!-- <th scope="col">ID</th> -->
                    <th scope="col">Número do lote</th>
                    <th scope="col">Baia</th>
                    <th scope="col">Animais</th>
                    <th scope="col">Nº de animais</th>
                    <th scope="col">Observação</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for lote in lotes %}
                <tr>
                    <!-- <td>{{ lote.id }}</td> -->
                    <td>{{ lote.numero }}</td>
                    <td>
                        {% if lote.baia %}
                        Baia {{ lote.baia.numero }}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>
                        {% if lote.get_animais %}
                        {% for animal in lote.get_animais %}
                        <span>{{ animal }}</span><br>
                        {% endfor %}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>
                        {{ lote.get_quantidade_animais }} 
                        {% if lote.get_quantidade_animais == 1 %}
                        animal
                        {% else %}
                        animais
                        {% endif %}
                    </td>
                    <td>
                        {% if lote.observacao %}
                        {{ lote.observacao }}
                        {% else %}
                        -
                        {% endif %}
                    <td>
                        <a class="text-decoration-none me-1" href="{% url 'pecuaria:atualizar_lote' lote.id %}" role="button">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="text-decoration-none btn-delete" href="{% url 'pecuaria:excluir_lote' lote.id %}" role="button">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

app/templates/pages/births.html
<!-- Template: pages/births.html -->

<!-- Extends Base Template -->
{% extends 'base/base.html' %}

<!-- Tab Title -->
{% block title %}Partos{% endblock title %}

<!-- Content -->
{% block content %}
<!-- Botão para cadastrar parto -->
<a class="btn btn-primary mb-3" href="{% url 'pecuaria:cadastrar_parto' %}" role="button">
    <i class="fas fa-plus me-1"></i>
    Cadastrar Parto
</a>

<!-- Tabela de partos -->
<div class="card p-3">
    <div class="table-responsive pb-3">
        <table id="table-pecuaria" class="table table-striped table-bordered nowrap align-middle text-center mb-0">
            <caption>Lista de partos</caption>
            <thead>
                <tr>
                    <!-- <th scope="col">ID</th> -->
                    <th scope="col">Data/Hora</th>
                    <th scope="col">Fêmea</th>
                    <th scope="col">Macho</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Vivos</th>
                    <th scope="col">Mortos</th>
                    <th scope="col">Mumificados</th>
                    <th scope="col">Nº de filhotes</th>
                    <th scope="col">Observação</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for parto in partos %}
                <tr>
                    <!-- <td>{{ parto.id }}</td> -->
                    <td>{{ parto.data_hora_do_parto|date:'d/m/Y \à\s H:i' }}</td>
                    <td>{{ parto.femea }}</td>
                    <td>{{ parto.macho }}</td>
                    <td>{{ parto.tipo }}</td>
                    <td>{{ parto.quantidade_de_filhotes_vivos }}</td>
                    <td>{{ parto.quantidade_de_filhotes_mortos }}</td>
                    <td>{{ parto.quantidade_de_filhotes_mumificados }}</td>
                    <td>
                        {{ parto.get_quantidade_filhotes }} 
                        {% if parto.get_quantidade_filhotes == 1 %}
                        filhote
                        {% else %}
                        filhotes
                        {% endif %}
                    </td>
                    <td>
                        {% if parto.observacao %}
                        {{ parto.observacao }}
                        {% else %}
                        -
                        {% endif %}
                    <td>
                        <a class="text-decoration-none me-1" href="{% url 'pecuaria:atualizar_parto' parto.id %}" role="button">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="text-decoration-none btn-delete" href="{% url 'pecuaria:excluir_parto' parto.id %}" role="button">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
        </table>
    </div>
</div>
{% endblock content %}

app/templates/pages/create_account.html
<!-- Template: pages/create_account.html -->

<!-- Extends Base Create Account Entry Template -->
{% extends 'base/base-create_account-entry.html' %}

<!-- Load Crispy Forms Tags -->
{% load crispy_forms_tags %}

<!-- Tab Title -->
{% block title %}Criar Conta{% endblock %}

<!-- Content -->
{% block content %}
<main class="form-signin w-100 m-auto">

    <!-- Messages -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" id="message">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
    
    <!-- UserCreationForm -->
    <form action="{% url 'pecuaria:create_account' %}" method="post" class="needs-validation" autocomplete="off" novalidate>
        <!-- CSRF Token -->
        {% csrf_token %}

        <!-- Form -->
        {{ form|crispy }}

        <!-- Submit Button and Link -->
        <div class="d-flex flex-column justify-content-center">
            <button type="submit" class="btn btn-primary">Criar Conta</button>
            <a href="{% url 'pecuaria:login' %}" class="btn btn-link mt-2">Já tenho uma conta</a>
        </div>
    </form>
</main>
{% endblock content %}

app/templates/pages/create_update_batch.html
<!-- Template: pages/create_update_batches.html -->

<!-- Extends Base Template -->
{% extends 'base/base.html' %}

<!-- Load Crispy Forms Tags -->
{% load crispy_forms_tags %}

<!-- Tab Title -->
{% block title %}
{% if request.path == '/pecuaria/lote/cadastrar/' %}
Cadastrar Lote
{% else %}
Atualizar Lote
{% endif %}
{% endblock title %}

<!-- Content -->
{% block content %}
<!-- Botão para voltar ou cancelar -->
<a class="btn btn-outline-success mb-3" href="{% url 'pecuaria:lotes' %}" role="button">
    {% if request.path == '/pecuaria/lote/cadastrar/' %}
    Voltar
    {% else %}
    Cancelar
    {% endif %}
</a>

<!-- Formulário de Lote -->
<form action="" method="post" id="lote-form" autocomplete="off" novalidate>
    {% csrf_token %}

    <div class="card">
        <div class="card-header">
            Informações do Lote
        </div>
        <div class="row p-3">
            <div class="col-12 col-sm">
                {{ lote_form.numero|as_crispy_field }}
            </div>
            <div class="col-12 col-sm">
                {{ lote_form.baia|as_crispy_field }}
            </div>
            <div class="col-12">
                {{ lote_form.observacao|as_crispy_field }}
            </div>
        </div>
    </div>
    
    <hr class="border border-success border-3 opacity-75">

    {{ animal_formset.management_form }}

    {% for form in animal_formset %}
    <div class="inlineform card my-3">
        <div class="card-header">
            Animal
        </div>
        <div class="row pt-3 px-3">
            {{ form|crispy }}
        </div>
    </div>
    {% endfor %}

    <div class="col-12 d-flex justify-content-center">
        <button class="btn btn-success w-100 mt-3" type="submit">
            {% if request.path == '/pecuaria/lote/cadastrar/' %}
            Salvar
            {% else %}
            Salvar Alterações
            {% endif %}
        </button>
    </div>
</form>
{% endblock content %}

<!-- JavaScript -->
{% block javascript %}
<script>
    $(document).ready(function () {
        // Adiciona e remove campos de formulário dinamicamente
        $('.inlineform').formset({
            prefix: '{{ animal_formset.prefix }}',
            addText: 'Adicionar novo Animal',
            deleteText: 'Remover este Animal',
            addCssClass: 'btn btn-primary w-100',
            deleteCssClass: 'btn btn-danger mx-3 mb-3',
        });
    });
</script>
{% endblock javascript %}

app/templates/pages/create_update_birth.html
<!-- Template: pages/create_update_births.html -->

<!-- Extends Base Template -->
{% extends 'base/base.html' %}

<!-- Load Crispy Forms Tags -->
{% load crispy_forms_tags %}

<!-- Tab Title -->
{% block title %}
{% if request.path == '/pecuaria/parto/cadastrar/' %}
Cadastrar Parto
{% else %}
Atualizar Parto
{% endif %}
{% endblock title %}

<!-- Content -->
{% block content %}
<!-- Botão para voltar ou cancelar -->
<a class="btn btn-outline-success mb-3" href="{% url 'pecuaria:partos' %}" role="button">
    {% if request.path == '/pecuaria/parto/cadastrar/' %}
    Voltar
    {% else %}
    Cancelar
    {% endif %}
</a>

<!-- Formulário de Parto -->
<form action="" method="post" id="parto-form" autocomplete="off" novalidate>
    {% csrf_token %}

    <div class="card">
        <div class="card-header">
            Informações do Parto
        </div>
        <div class="row p-3">
            <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                {{ parto_form.femea|as_crispy_field }}
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                {{ parto_form.macho|as_crispy_field }}
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                {{ parto_form.data_hora_do_parto|as_crispy_field }}
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                {{ parto_form.tipo|as_crispy_field }}
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-4">
                {{ parto_form.quantidade_de_filhotes_vivos|as_crispy_field }}
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-4">
                {{ parto_form.quantidade_de_filhotes_mortos|as_crispy_field }}
            </div>
            <div class="col-12 col-sm-12 col-md col-lg-4">
                {{ parto_form.quantidade_de_filhotes_mumificados|as_crispy_field }}
            </div>
            <div class="col-12">
                {{ parto_form.observacao|as_crispy_field }}
            </div>
        </div>
    </div>
    
    <hr class="border border-success border-3 opacity-75">

    {{ animal_formset.management_form }}

    {% for form in animal_formset %}
    <div class="inlineform card my-3">
        <div class="card-header">
            Animal
        </div>
        <div class="row pt-3 px-3" id="fields-container">
            {{ form|crispy }}
        </div>
    </div>
    {% endfor %}

    <div class="col-12 d-flex justify-content-center">
        <button class="btn btn-success w-100 mt-3" type="submit">
            {% if request.path == '/pecuaria/parto/cadastrar/' %}
            Salvar
            {% else %}
            Salvar Alterações
            {% endif %}
        </button>
    </div>
</form>
{% endblock content %}

<!-- JavaScript -->
{% block javascript %}
<script>
    $(document).ready(function () {
        // Formset para adicionar e remover animais
        $('.inlineform').formset({
            prefix: '{{ animal_formset.prefix }}',
            addText: 'Adicionar novo Animal',
            deleteText: 'Remover este Animal',
            addCssClass: 'btn btn-primary w-100',
            deleteCssClass: 'btn btn-danger mx-3 mb-3',
        });
    });
</script>
{% endblock javascript %}

app/templates/pages/create_update_handling.html
<!-- Template: pages/create_update_handling.html -->

<!-- Extends Base Template -->
{% extends 'base/base.html' %}

<!-- Load Crispy Forms Tags -->
{% load crispy_forms_tags %}

<!-- Tab Title -->
{% block title %}
{% if request.path == '/pecuaria/manejo/cadastrar/' %}
Cadastrar Manejo
{% else %}
Atualizar Manejo
{% endif %}
{% endblock title %}

<!-- Content -->
{% block content %}
<!-- Botão para voltar ou cancelar -->
<a class="btn btn-outline-success mb-3" href="{% url 'pecuaria:manejos' %}" role="button">
    {% if request.path == '/pecuaria/manejo/cadastrar/' %}
    Voltar
    {% else %}
    Cancelar
    {% endif %}
</a>

<!-- Formulário de Manejo -->
<form action="" method="post" id="manejo-form" autocomplete="off" novalidate>
    {% csrf_token %}

    <div class="card">
        <div class="card-header">
            Informações do Manejo
        </div>
        <div class="row p-3">
            <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                {{ manejo_form.funcionario|as_crispy_field }}
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                {{ manejo_form.data_hora_do_manejo|as_crispy_field }}
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                {{ manejo_form.animal|as_crispy_field }}
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                {{ manejo_form.lote|as_crispy_field }}
            </div>
            <div class="col-12">
                {{ manejo_form.observacao|as_crispy_field }}
            </div>
        </div>
    </div>
    <hr class="border border-success border-3 opacity-75 mb-0">
    <div class="row">
        <div class="col-md-6">
            {{ procedimento_formset.management_form }}

            {% for form in procedimento_formset %}
            <div class="inlineform-procedimento card my-3">
                <div class="card-header">
                    Informações do Procedimento
                </div>
                <div class="row pt-3 px-3">
                    {{ form|crispy }}
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- <hr class="border border-success border-3 opacity-75"> -->
        <div class="col-md-6">
            {{ produto_formset.management_form }}

            {% for form in produto_formset %}
            <div class="inlineform-produto card my-3">
                <div class="card-header">
                    Informações do Produto
                </div>
                <div class="row pt-3 px-3">
                    {{ form|crispy }}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="col-12 d-flex justify-content-center">
        <button class="btn btn-success w-100 mt-3" type="submit">
            {% if request.path == '/pecuaria/manejo/cadastrar/' %}
            Salvar
            {% else %}
            Salvar Alterações
            {% endif %}
        </button>
    </div>
</form>
{% endblock content %}

<!-- JavaScript -->
{% block javascript %}
<script>
    $(document).ready(function () {
        // Formset para adicionar e remover procedimentos
        $('.inlineform-procedimento').formset({
            prefix: '{{ procedimento_formset.prefix }}',
            addText: 'Adicionar novo Procedimento',
            deleteText: 'Remover este Procedimento',
            addCssClass: 'btn btn-primary w-100',
            deleteCssClass: 'btn btn-danger mx-3 mb-3',
        });
        
        // Formset para adicionar e remover produtos
        $('.inlineform-produto').formset({
            prefix: '{{ produto_formset.prefix }}',
            addText: 'Adicionar novo Produto',
            deleteText: 'Remover este Produto',
            addCssClass: 'btn btn-primary w-100',
            deleteCssClass: 'btn btn-danger mx-3 mb-3',
        });
    });
</script>
{% endblock javascript %}

app/templates/pages/error_page.html
<!-- Template: pages/error_page.html -->

<!-- Extends Base Error Page Template -->
{% extends 'base/base-error_page.html' %}

<!-- Tab Title -->
{% block title %}{{ status_code }} - Erro{% endblock title %}

<!-- CSS -->
{% block css %}
<style>
    .content {
        border: 1px solid #ddd;
        background-color: #f9f9f9;
    }

    h1 {
        font-size: 48px;
        margin-bottom: 20px;
    }

    p {
        font-size: 18px;
        margin-bottom: 30px;
    }

    .btn-home {
        padding: 10px 20px;
        font-size: 16px;
        background-color: #007bff;
        color: white;
        text-decoration: none;
        border-radius: 5px;
    }

    .btn-home:hover {
        background-color: #0056b3;
    }
</style>
{% endblock css %}

<!-- Content -->
{% block content %}
<div class="content text-center p-5 rounded">
    <h1>{{ status_code }}</h1>
    <p>{{ message }}</p>
    <a href="{% url 'pecuaria:home' %}" class="btn-home">Voltar para a Home</a>
</div>
{% endblock content %}

app/templates/pages/handlings.html
<!-- Template: pages/handlings.html -->

<!-- Extends Base Template -->
{% extends 'base/base.html' %}

<!-- Tab Title -->
{% block title %}Manejos{% endblock title %}

<!-- Content -->
{% block content %}
<!-- Botão para cadastrar manejo -->
<a class="btn btn-primary mb-3" href="{% url 'pecuaria:cadastrar_manejo' %}" role="button">
    <i class="fas fa-plus me-1"></i>
    Cadastrar Manejo
</a>

<!-- Tabela de manejos -->
<div class="card p-3">
    <div class="table-responsive pb-3">
        <table id="table-pecuaria" class="table table-striped table-bordered nowrap align-middle text-center mb-0">
            <caption>Lista de manejos</caption>
            <thead>
                <tr>
                    <!-- <th scope="col">ID</th> -->
                    <th scope="col">Data/Hora</th>
                    <th scope="col">Funcionário</th>
                    <th scope="col">Animal</th>
                    <th scope="col">Lote</th>
                    <th scope="col">Procedimentos</th>
                    <th scope="col">Produtos</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for manejo in manejos %}
                <tr>
                    <!-- <td>{{ manejo.id }}</td> -->
                    <td>{{ manejo.data_hora_do_manejo|date:'d/m/Y \à\s H:i' }}</td>
                    <td>{% if manejo.funcionario %}
                        {{ manejo.funcionario }}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>
                        {% if manejo.animal %}
                        {{ manejo.animal.identificacao_unica }}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>
                        {% if manejo.lote %}
                        Lote {{ manejo.lote.numero }}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>
                        {% if manejo.procedimento_manejo.exists %}
                        {% for procedimento in manejo.procedimento_manejo.all %}
                        <span>{{ procedimento.procedimento }}</span><br>
                        {% endfor %}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>
                        {% if manejo.produto_manejo.exists %}
                        {% for produto in manejo.produto_manejo.all %}
                        <span>{{ produto.produto }}</span><br>
                        {% endfor %}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>
                        <a class="text-decoration-none me-1" href="{% url 'pecuaria:atualizar_manejo' manejo.id %}" role="button">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="text-decoration-none btn-delete" href="{% url 'pecuaria:excluir_manejo' manejo.id %}" role="button">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

app/templates/pages/login.html
<!-- Template: pages/login.html -->

<!-- Extends Base Create Account Entry Template -->
{% extends 'base/base-create_account-entry.html' %}

<!-- Load Crispy Forms Tags -->
{% load crispy_forms_tags %}

<!-- Tab Title -->
{% block title %}Entrar{% endblock %}

<!-- Content -->
{% block content %}
<main class="form-signin w-100 m-auto">
    <!-- Messages -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" id="message">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
    
    <!-- AuthenticationForm -->
    <form action="{% url 'pecuaria:login' %}" method="post" class="needs-validation" autocomplete="off" novalidate>
        <!-- CSRF Token -->
        {% csrf_token %}

        <!-- Form -->
        {{ form|crispy }}

        <!-- Submit Button and Link -->
        <div class="d-flex flex-column justify-content-center">
            <button type="submit" class="btn btn-primary">Entrar</button>
            <a href="{% url 'pecuaria:create_account' %}" class="btn btn-link mt-2">Criar uma conta</a>
        </div>
    </form>
</main>
{% endblock content %}

app/templates/pages/outputs.html
<!-- Template: pages/outputs.html -->

<!-- Extends Base Template -->
{% extends 'base/base.html' %}

<!-- Tab Title -->
{% block title %}Saídas{% endblock title %}

<!-- Content -->
{% block content %}
<!-- Botão para cadastrar saída -->
<a class="btn btn-primary mb-3" href="{% url 'pecuaria:cadastrar_saida' %}" role="button">
    <i class="fas fa-plus me-1"></i>
    Cadastrar Saída
</a>

<!-- Tabela de saídas -->
<div class="card p-3">
    <div class="table-responsive pb-3">
        <table id="table-pecuaria" class="table table-striped table-bordered nowrap align-middle text-center mb-0">
            <caption>Lista de saídas</caption>
            <thead>
                <tr>
                    <th scope="col">Data/Hora</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Animais</th>
                    <th scope="col">Nº de animais</th>
                    <th scope="col">Observação</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for saida in saidas %}
                <tr>
                    <td>{{ saida.data_hora_da_saida|date:'d/m/Y \à\s H:i' }}</td>
                    <td>{{ saida.tipo }}</td>
                    <td>
                        {% if saida.get_animais %}
                        {% for animal in saida.get_animais %}
                        <span>{{ animal }}</span><br>
                        {% endfor %}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>
                        {{ saida.get_quantidade_animais }} 
                        {% if saida.get_quantidade_animais == 1 %}
                        animal
                        {% else %}
                        animais
                        {% endif %}
                    </td>
                    <td>
                        {% if saida.observacao %}
                        {{ saida.observacao }}
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>
                        <a class="text-decoration-none me-1" href="{% url 'pecuaria:atualizar_saida' saida.id %}" role="button">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="text-decoration-none btn-delete" href="{% url 'pecuaria:excluir_saida' saida.id %}" role="button">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}