app/urls.py
from app.views import *
from django.urls import path

app_name = 'pecuaria'

urlpatterns = [
    path('erro/', error_page, name='error_page'), # Rota para página de erro
    path('criar-conta/', create_account, name='create_account'), # Rota para criar conta
    path('entrar/', login_view, name='login'), # Rota para login
    path('sair/', logout_view, name='logout'), # Rota para logout
    path('', home, name='home'), # Rota para home
    path('lotes/', lotes, name='lotes'), # Rota para página de visualização de lotes
    path('lote/cadastrar/', cadastrar_lote, name='cadastrar_lote'), # Rota para página de cadastro de lotes
    path('lote/atualizar/<int:id>/', atualizar_lote, name='atualizar_lote'), # Rota para página de atualização de lotes
    path('lote/excluir/<int:id>/', excluir_lote, name='excluir_lote'), # Rota que permite excluir um lote
    path('partos/', partos, name='partos'), # Rota para página de visualização de partos
    path('parto/cadastrar/', cadastrar_parto, name='cadastrar_parto'), # Rota para página de cadastro de partos
    path('parto/atualizar/<int:id>/', atualizar_parto, name='atualizar_parto'), # Rota para página de atualização de partos
    path('parto/excluir/<int:id>/', excluir_parto, name='excluir_parto'), # Rota que permite excluir um parto
    path('manejos/', manejos, name='manejos'), # Rota para página de visualização de manejos
    path('manejo/cadastrar/', cadastrar_manejo, name='cadastrar_manejo'), # Rota para página de cadastro de manejos
    path('manejo/atualizar/<int:id>/', atualizar_manejo, name='atualizar_manejo'), # Rota para página de atualização de manejos
    path('manejo/excluir/<int:id>/', excluir_manejo, name='excluir_manejo'), # Rota que permite excluir um manejo
    path('saidas/', saidas, name='saidas'), # Rota para página de visualização de saídas
    path('saida/cadastrar/', cadastrar_saida, name='cadastrar_saida'), # Rota para página de cadastro de saídas
    path('saida/atualizar/<int:id>/', atualizar_saida, name='atualizar_saida'), # Rota para página de atualização de saídas
    path('saida/excluir/<int:id>/', excluir_saida, name='excluir_saida'), # Rota que permite excluir uma saída
    path('animais/', animais, name='animais'), # Rota para página de visualização de animais
    path('animal/', animal_info, name='animal_info'), # Rota para página de visualização das informações de um animal via RFID

    path('api/animal/<str:rfid>/', get_animal, name='get_animal'), # Rota para comunicar com o ESP 8266
    path('api/latest-animal/', latest_animal, name='latest_animal'), # Rota para retornar o último animal lido
]

dev-pecuaria-antigo/apps/feedback/urls.py
from django.urls import path
from .views import * 

urlpatterns = [
    path('feedback/<str:code>', home, name="index"),
    path('feedback/salvarAnswer/', salvarAnswer, name="salvarAnswer"),
]

dev-pecuaria-antigo/config/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

urlpatterns = [
    path("", include("apps.core.urls")),
    path('api-auth/', include('rest_framework.urls'), name='rest_framework'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('pecuaria/', include('app.urls')),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dev-pecuaria-antigo/apps/feedback/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class Questionario(models.Model):
    nome = models.CharField(max_length=255 ,null=True)
    objetivo = models.TextField(null=True)
    owner = models.CharField(max_length=50, null=True, verbose_name="Criado_por")
    created_at = models.DateTimeField(null=True, auto_now_add=True)
    last_update = models.DateTimeField(null=True, auto_now_add=True)
    link = models.CharField(max_length=25, null=True)
    link_resposta = models.CharField(max_length=25, null=True)
    
    def __str__(self):
        return self.nome
    
class Type(models.Model):
    type_choices = [
        ('text', 'text'),
        ('textarea', 'textarea'),
        ('radio', 'radio'),
        ('checkbox', 'checkbox'),
        ('select', 'select'),
    ]
    tipo = models.CharField(max_length=50, choices=type_choices, unique=True)

    def __str__(self):
        return self.tipo

class Questao(models.Model):
    title = models.TextField(null=True, verbose_name="Nome")
    tipo = models.ForeignKey(Type, on_delete=models.CASCADE)
    questionario_id = models.ForeignKey(Questionario, on_delete=models.CASCADE)
    # tipo, se a questão tem como resposta texto, multiplas respostas, seleção única, ou caixa de seleção
    # 1 = area
    # 2 = textarea
    # 3 = radio
    # 4 = checkbox
    # 5 = select
    
    class Meta:
        verbose_name = _("Questão")
        verbose_name_plural = _("Questões")

    def __str__(self):
        return str(self.title)

class Alternativa(models.Model):
    title = models.TextField(null=True, verbose_name="Nome")
    questao_id = models.ForeignKey(Questao, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.title)
    
class Answer(models.Model):
    questionario_id = models.ForeignKey(Questionario, on_delete=models.CASCADE)
    questao_id = models.ForeignKey(Questao, on_delete=models.CASCADE)
    answer = models.CharField(max_length=255, null=True)
    
    
    # user_id = models.IntegerField(null=True, blank=True)
    
    def __str__(self):
        return self.answer

dev-pecuaria-antigo/apps/feedback/views.py
from django.shortcuts import render
from .models import *
from django.db.models import Max, Count
from django.http import Http404
import json
from django.http import JsonResponse
from django.db import connection


def teste(request):
    return render(
        request,
        "teste.html",
    )

def home(request, code):
    try:
        # Tente buscar pelo campo 'link'
        u_questionario = Questionario.objects.get(link=code)
        template_name = "form.html"  # Usar template para link
    except Questionario.DoesNotExist:
        try:
            # Se não encontrado, tente buscar pelo campo 'link_resposta'
            u_questionario = Questionario.objects.get(link_resposta=code)
            
            # Filtra as respostas pelo questionário especificado
            respostas = Answer.objects.filter(questionario_id=u_questionario).order_by('questao_id')

            # Anota as respostas agrupadas por questão, tipo e valor
            respostas_agrupadas = respostas.values('questao_id__title', 'questao_id__tipo__tipo', 'answer').annotate(count=Count('answer'))

            # Transforma o QuerySet em uma estrutura de dados que pode ser iterada no template
            resultados = {}
            for resposta in respostas_agrupadas:
                questao = resposta['questao_id__title']
                tipo = resposta['questao_id__tipo__tipo']
                answer = resposta['answer']
                count = resposta['count']
                if questao in resultados:
                    resultados[questao].append({'tipo': tipo, 'answer': answer, 'count': count})
                else:
                    resultados[questao] = [{'tipo': tipo, 'answer': answer, 'count': count}]

            # Renderiza o template HTML com os resultados
            return render(request, 'resposta.html', {'u_questionario': u_questionario,'resultados': resultados})

        except Questionario.DoesNotExist:
            raise Http404("Questionário não encontrado")

    quests = Questao.objects.filter(questionario_id=u_questionario)
    return render(
        request,
        template_name,
        {"u_questionario": u_questionario, "quests": quests},
    )

def salvarAnswer(request):
    try:
        # Crie um objeto Questionario com o nome
        questionario = Questionario.objects.get(
            id=int(request.POST.get("idQuestionario"))
        )

        # Decodificar os arrays do JSON
        array_pergunta = json.loads(request.POST.get("arrayP"))
        # array_pergunta = request.POST.get("arrayP")

        print(array_pergunta)
        # Itere pelas perguntas e crie objetos Questao associados ao questionário
        for a in array_pergunta:
            resp = request.POST.get(a)
            questao = Questao.objects.get(id=a)

            # Crie a pergunta
            resposta = Answer(
                questionario_id=questionario, questao_id=questao, answer=resp
            )
            resposta.save()

        # Redirecione para a página de sucesso ou faça o que for necessário
        return render(request, "answer.html")

    except Exception as e:
        # Em caso de erro, redirecione para uma página de erro
        # return HttpResponse(
        # '<script>alert("Não foi possível responder, tente novamente - - - error_message"); window.location.href = "javascript:history.back()";</script>'
        # )
        error_message = f"Erro ao salvar o questionário: {str(e)}"
        return render(request, "form.html", {"error_message": error_message})

dev-pecuaria-antigo/apps/feedback/templates/answer.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulário Respondido com Sucesso</title>
    <style>
        body{
            display: flex;
            height: 80vh;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <h1>Formulário Respondido com Sucesso!</h1>
</body>
</html>

dev-pecuaria-antigo/apps/feedback/templates/form.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <title>Responder Questionário</title>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <style>
    .shaded-box {
  box-shadow: 0px 0px 15px 5px rgba(0, 0, 0, 0.5);
}
.a {
  border: 2px solid black;
}
  </style>
</head>

<body class="bg-success.bg-gradient">

  <main class="container mt-4 d-flex flex-column align-items-center justify-content-center">
    {% if error_message %}
      <script>
        alert("{{ error_message }}");
      </script>
    {% endif %}

    <div id="ViewForm" class="form-container p-4 rounded shaded-box col-md-6">
      <form method="POST" action="{% url 'salvarAnswer' %}" onsubmit="atualizarCamposHidden()"
        class="bg-light p-4 rounded">
        {% csrf_token %}
        <div class="mb-1 d-flex flex-column align-items-center">
          <h1 class="mb-4">{{ u_questionario.nome }}</h1>
          <p>{{ u_questionario.objetivo }}</p>
        </div>
        {% for quest in quests %}
          <div class="mb-3">
            {% if quest.tipo.tipo == "text" %}
              <label for="{{ quest.id }}" class="form-label bold">{{ quest.title }}</label>
              <input type="text" name="{{ quest.id }}" id="{{ quest.id }}" placeholder="{{ quest.title }}"
                class="form-control" required>
            {% elif quest.tipo.tipo == "textarea" %}
              <label for="{{ quest.id }}" class="form-label bold">{{ quest.title }}</label>
              <textarea id="{{ quest.id }}" name="{{ quest.id }}" rows="4" cols="50"
                class="form-control" required></textarea>
            {% elif quest.tipo.tipo == "selectbox" or quest.tipo.tipo == "select" %}
              <label for="{{ quest.id }}" class="form-label bold">{{ quest.title }}</label>
              <select name="{{ quest.id }}" class="form-select" required>
                {% for alternative in quest.alternativa_set.all %}
                  <option value="{{ alternative.title }}">{{ alternative.title }}</option>
                {% endfor %}
              </select>
            {% elif quest.tipo.tipo == "radio" %}
              <p class="bold">{{ quest.title }}</p>
              <input type="hidden" id="{{ quest.id }}">
              {% for alternative in quest.alternativa_set.all %}
                <div class="form-check">
                  <input type="radio" name="{{ quest.id }}" value="{{ alternative.title }}"
                    id="alt_{{ alternative.id }}" class="form-check-input a">
                  <label for="alt_{{ alternative.id }}" class="form-check-label">{{ alternative.title }}</label>
                </div>
              {% endfor %}
            {% elif quest.tipo.tipo == "checkbox" %}
              <p class="bold">{{ quest.title }}</p>
              <input type="hidden" id="{{ quest.id }}">
              {% for alternative in quest.alternativa_set.all %}
                <div class="form-check">
                  <input type="checkbox" name="{{ quest.id }}" value="{{ alternative.title }}"
                    id="alt_{{ alternative.id }}" class="form-check-input">
                  <label for="alt_{{ alternative.id }}" class="form-check-label">{{ alternative.title }}</label>
                </div>
              {% endfor %}
            {% endif %}
          </div>
        {% endfor %}
        <input type="hidden" name="arrayP" id="arrayP" value="">
        <input type="hidden" name="idQuestionario" id="idQuestionario" value="{{ u_questionario.id }}">
        <div class="d-flex flex-column align-items-center">
          <button type="submit" class="btn btn-primary">Enviar Resposta</button>
        </div>
      </form>
    </div>
  </main>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
    crossorigin="anonymous"></script>
  <script>
    var arrayP = [];

    // Essa função será chamada quando o formulário for enviado para atualizar os campos hidden.
    function atualizarCamposHidden() {

      arrayP.length = 0;
      // Obtenha todos os campos do formulário
      var formElements = document.querySelectorAll('form input[type="text"], form textarea, form select, form input[type="hidden"]');

      // Itere pelos campos e adicione as informações aos arrays
      formElements.forEach(function (element) {
        arrayP.push(element.id)
      });
      arrayP.splice(0, 1); // Remove 3 elementos a partir do índice 1 (valores 2, 3, 4)
      // Atualize os campos hidden com os arrays
      arrayP.pop()
      arrayP.pop()
      console.log(arrayP)
      document.getElementById("arrayP").value = JSON.stringify(arrayP);
    }
  </script>
</body>

</html>

dev-pecuaria-antigo/apps/feedback/templates/resposta.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>Responder Questionário</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    
    <style>
        .shaded-box {
            box-shadow: 0px 0px 15px 5px rgba(0, 0, 0, 0.5);
        }
    </style>
</head>

<body class="bg-success.bg-gradient">

    <main class="container mt-4 d-flex flex-column align-items-center justify-content-center">
        {% if error_message %}
        <script>
            alert("{{ error_message }}");
        </script>
        {% endif %}

        <div class="form-container p-4 rounded shaded-box col-md-6">
            <div class="mb-1 d-flex flex-column align-items-center">
                <h1 class="mb-4">{{ u_questionario.nome }}</h1>
                <p>{{ u_questionario.objetivo }}</p>
                
            </div>
            {% for questao, respostas in resultados.items %}

            {% if respostas.0.tipo == "text" or respostas.0.tipo == "textarea" %}
            <p class="fw-bold fs-5">{{ questao }}</p>
            <table class="table table-bordered table-striped text-center align-middle">
                <thead>
                    <tr>
                        <th>Resposta</th>
                        <th>Quantidade</th>
                    </tr>
                </thead>
                <tbody>
                    {% for resposta in respostas %}
                    <tr>
                        <td>{{ resposta.answer }}</td>
                        <td>{{ resposta.count }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            {% elif respostas.0.tipo == "radio" or respostas.0.tipo == "checkbox" or respostas.0.tipo == "select" %}
            <p class="fw-bold fs-5">{{ questao }}</p>


            <div id="{{ questao }}"></div>

            <script type="text/javascript">
                google.charts.load('current', {'packages':['corechart']});
                google.charts.setOnLoadCallback(drawChart);
          
                function drawChart() {
          
                  var data = google.visualization.arrayToDataTable([
                    ['Respostas', 'Quantidade'],
                    {% for resposta in respostas %}
                        ['{{ resposta.answer}}', {{ resposta.count }} ],
                    {% endfor %}
                  ]);
          
                  var chart = new google.visualization.PieChart(document.getElementById('{{ questao }}'));
          
                  chart.draw(data);
                }
              </script>
            

            {% endif %}
            {% endfor %}
        </div>
    </main>
    <script>
        // Array de cores em hexadecimal
        var cores = ["#FF5733", "#FF3333", "#FF33A8", "#3387FF", "#33FF42", "#33FFAD"];

        // Variável para controlar a cor
        var i = 0;

        // Função para obter a próxima cor
        function obterProximaCor() {
            if (i >= cores.length) {
                // Reinicia o índice das cores quando atingir o final
                i = 0;
            }
            return cores[i++];
        }
    </script>


</body>

</html>