app/urls.py
from app.views import *
from django.urls import path

app_name = 'pecuaria'

urlpatterns = [
    path('erro/', error_page, name='error_page'), # Rota para página de erro
    path('criar-conta/', create_account, name='create_account'), # Rota para criar conta
    path('entrar/', login_view, name='login'), # Rota para login
    path('sair/', logout_view, name='logout'), # Rota para logout
    path('', home, name='home'), # Rota para home
    path('lotes/', lotes, name='lotes'), # Rota para página de visualização de lotes
    path('lote/cadastrar/', cadastrar_lote, name='cadastrar_lote'), # Rota para página de cadastro de lotes
    path('lote/atualizar/<int:id>/', atualizar_lote, name='atualizar_lote'), # Rota para página de atualização de lotes
    path('lote/excluir/<int:id>/', excluir_lote, name='excluir_lote'), # Rota que permite excluir um lote
    path('partos/', partos, name='partos'), # Rota para página de visualização de partos
    path('parto/cadastrar/', cadastrar_parto, name='cadastrar_parto'), # Rota para página de cadastro de partos
    path('parto/atualizar/<int:id>/', atualizar_parto, name='atualizar_parto'), # Rota para página de atualização de partos
    path('parto/excluir/<int:id>/', excluir_parto, name='excluir_parto'), # Rota que permite excluir um parto
    path('manejos/', manejos, name='manejos'), # Rota para página de visualização de manejos
    path('manejo/cadastrar/', cadastrar_manejo, name='cadastrar_manejo'), # Rota para página de cadastro de manejos
    path('manejo/atualizar/<int:id>/', atualizar_manejo, name='atualizar_manejo'), # Rota para página de atualização de manejos
    path('manejo/excluir/<int:id>/', excluir_manejo, name='excluir_manejo'), # Rota que permite excluir um manejo
    path('saidas/', saidas, name='saidas'), # Rota para página de visualização de saídas
    path('saida/cadastrar/', cadastrar_saida, name='cadastrar_saida'), # Rota para página de cadastro de saídas
    path('saida/atualizar/<int:id>/', atualizar_saida, name='atualizar_saida'), # Rota para página de atualização de saídas
    path('saida/excluir/<int:id>/', excluir_saida, name='excluir_saida'), # Rota que permite excluir uma saída
    path('animais/', animais, name='animais'), # Rota para página de visualização de animais
    path('animal/', animal_info, name='animal_info'), # Rota para página de visualização das informações de um animal via RFID

    path('api/animal/<str:rfid>/', get_animal, name='get_animal'), # Rota para comunicar com o ESP 8266
    path('api/latest-animal/', latest_animal, name='latest_animal'), # Rota para retornar o último animal lido
]

dev-pecuaria-antigo/config/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

urlpatterns = [
    path("", include("apps.core.urls")),
    path('api-auth/', include('rest_framework.urls'), name='rest_framework'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('pecuaria/', include('app.urls')),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/partials/footer.html
<!-- Partials: partials/footer.html -->

<!-- Footer -->
<footer class="mt-3 py-4 bg-light">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-center small">
            <div class="text-muted">Copyright &copy; {% now "Y" %}</div>
        </div>
    </div>
</footer>

app/templates/partials/header.html
<!-- Partials: partials/header.html -->

<!-- Load Static Files -->
{% load static %}

<!-- Header -->
<header class="fixed-top">
    <nav class="navbar navbar-expand-md navbar-dark bg-success">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample"
                aria-controls="navbarsExample" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand text-uppercase fw-bold col-md-3 me-0 d-block d-md-none" href="#">
                Pecuária
                <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
            </a>
            <div class="collapse navbar-collapse d-md-flex" id="navbarsExample">
                <a class="navbar-brand text-uppercase fw-bold col-md-3 me-0 d-none d-md-block" href="#">
                    Pecuária
                    <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
                </a>
                <ul class="navbar-nav col-md-6 justify-content-md-center">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/pecuaria/' %}active fw-bold{% endif %}"
                            href="{% url 'pecuaria:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/pecuaria/lotes/' or '/pecuaria/lote/cadastrar/' in request.path or '/pecuaria/lote/atualizar/' in request.path %}active fw-bold{% endif %}"
                            href="{% url 'pecuaria:lotes' %}">Lotes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/pecuaria/partos/' or '/pecuaria/parto/cadastrar/' in request.path or '/pecuaria/parto/atualizar/' in request.path %}active fw-bold{% endif %}"
                            href="{% url 'pecuaria:partos' %}">Partos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/pecuaria/manejos/' or '/pecuaria/manejo/cadastrar/' in request.path or '/pecuaria/manejo/atualizar/' in request.path %}active fw-bold{% endif %}"
                            href="{% url 'pecuaria:manejos' %}">Manejos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/pecuaria/saidas/' or '/pecuaria/saida/cadastrar/' in request.path or '/pecuaria/saida/atualizar/' in request.path %}active fw-bold{% endif %}"
                            href="{% url 'pecuaria:saidas' %}">Saídas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/pecuaria/animais/' %}active fw-bold{% endif %}"
                            href="{% url 'pecuaria:animais' %}">Animais</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/pecuaria/animal/' %}active fw-bold{% endif %}"
                            href="{% url 'pecuaria:animal_info' %}">Ver Animal</a>
                    </li>
                </ul>
                {% if user.is_authenticated %}
                    <div class="d-md-flex col-md-3 justify-content-md-end">
                        <a href="{% url 'pecuaria:logout' %}" class="btn btn-outline-light btn-logout">Sair</a>
                    </div>
                {% else %}
                    <div class="d-md-flex col-md-3 justify-content-md-end">
                        <a href="{% url 'pecuaria:login' %}" class="btn btn-outline-light btn-login">Entrar</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </nav>
</header>